version: "3"
services:
  the-forest-server-01:
    container_name: the-forest-server-01
    image: donimax/theforest-docker:latest
    restart: unless-stopped
    ports:
      - 8766:8766/tcp
      - 8766:8766/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - '/opt/docker/theforest/config:/config'
    environment:
      - SERVERSTEAMACCOUNT=bal
